version: "3"
services:
  test:
    build:
      context: ./playwright

  robot:
    build:
      context: ./robotframework
    volumes:
      - ./frontend-test-report:/app/report
    environment:
      - FRONTEND_URL=${FRONTEND_URL:-https://www.google.com}

  web:
    build:
      context: ./demo-web
      dockerfile: Dockerfile
    image: web:4.0
    ports:
      - "9999:80"