version: "3"
services:
  test:
    build:
      context: ./playwright
    environment:
      - PLAYWRIGHT_JUNIT_OUTPUT_NAME=/reports/results.xml
    volumes:
      - ./playwright-test-report:/reports

  robot:
    build:
      context: ./robotframework
    volumes:
      - ./robot-test-report:/app/report
    environment:
      - FRONTEND_URL=${FRONTEND_URL:-https://www.google.com}
  
  api_test:
    build: ./postman
    tty: true
    volumes:
      - ./api-test-report:/etc/newman/newman

  web:
    build:
      context: ./demo-web
      dockerfile: Dockerfile
    image: web:4.0
    restart: always
    ports:
      - "9999:80"